@startuml
  Class Almacen{
    +String Direccion;
    void Alta(Cuadro);
    void Baja(Cuadro);
    void Consulta(Cuadro);
  }

  Class Comprador{
    +String nombre;
    void Comprar(Cuadro);
  }

  Class Vendedor{
    +String nombre;
    void Vender(Cuadro);
  }

  Class Cuadro{
    +String Descripcion;
    +String Artista
  }

  Class Compra{
    +String Comprador;
    +String Direccion;
    -Int Precio;
  }

  Class Venta{
    +String Vendedor;
    +String Direccion;
    +String Precio;
    -int anio;
    +String Artista;
  }

  Class Reporte{
    +String Tipo De Obra;
    +String Artista;
    +String Precio;
    -int anio;
    void Alta(Cuadro, Tipo, Costo, Fecha);
    void Baja(Cuadro, Tipo, Costo, Fecha);
    void Consulta(Cuadro, Artista, Tipo, Precio, Fecha);
  }

  Comprador -- Cuadro : adquiere >
  Comprador -- Compra : realiza >
  Vendedor -- Cuadro : vende >
  Vendedor -- Venta : realiza >
  Almacen -- Cuadro : tiene >
  Compra -- Reporte : genera >
  Venta -- Reporte : genera >
  Compra *-- Cuadro : tiene n >
  Venta *-- Cuadro : tiene n >
@enduml
